### ISSUE TITLE
Connection Problem

### ISSUE THREAD

**Issue by Timme-72** [scheidtdav/homeassistant-kostal-piko#11]
Hello, I have PIKO 5.5 with FW 5.44
 and before I checked this one https://github.com/rcasula/kostalpiko-homeassistant
that was connect without problems.

Than I would like to try yours.

After
HOST: http://192.168.178.XX
USER: pvserver
PW: XXXXXXX

It came to no connection possible

![Fehler](https://github.com/scheidtdav/homeassistant-kostal-piko/assets/155076395/64c89bee-b123-46fe-b413-8ad71b4f4aa4)

**Comment by scheidtdav** [comment]
Hey,

thats weird. Any chance you can provide some of the logs? That would help out a lot.

Cheers

**Comment by Timme-72** [comment]
Hi,
I think something went wrong by deleting "rcasual" - that somewhere is fixed the host ip.
After deleting I can't install the first one as well - similar problem that the host is blocked.

**Comment by molelightn** [comment]
Hi, 

need to say that i have the same problem with "verbindung zum Inverter kann nicht hergestellt werden" with the integration provided in this repo.

I did try it with all different kind of HACS integrations for Kostal Piko, even the [one](https://github.com/rcasula/kostalpiko-homeassistant/pull/29) here which has fixed issue for "unique ID".

It came to:

![image](https://github.com/scheidtdav/homeassistant-kostal-piko/assets/62118239/b0b9b631-3839-467a-a68f-2718374ca4de)


Sorry is a little of topic but maybe in relation with. 
Unfortunately i cannot provide informations to the software version from piko inverters. I do have rare access to them.

br

**Comment by scheidtdav** [comment]
While developing this integration I did notice that the inverter would block requests from time to time. I think this might be some sort of rate limiting to prevent flooding the inverter with requests, because it only happened when the update interval was smaller than 15 seconds. Having the inverters web page open does add to it though, so even 15 seconds is not perfectly safe.
It usually stopped happening after a while however (maybe 15 minutes or so).

Could be possible that there was just "too much going on" with both integrations installed, @Timme-72 ?
Does it maybe work today? Do you have multiple inverters running, so the issue @molelightn may be the cause?

Btw: @molelightn thanks for the input. I am not sure if this integration is affected by that, it _should_ ™️assign the entities to the correct devices based on the inverters serial no. Have you tried? If so, please feel free to open a new issue :)

**Comment by Timme-72** [comment]
Hey,
the https://github.com/rcasula/kostalpiko-homeassistant is still working

BR

**Comment by scheidtdav** [comment]
Ah I didn't catch that, sorry.
Could you provide some context from the logs (Settings > System > Logs) and paste it here please?
Otherwise I reckon its pretty hard to figure this out just from the screenshot.

Thanks in advance!

**Comment by scheidtdav** [comment]
I just realized this: The version from @rcasula is using a python package that was forked from the package that originally gave me the idea to build my own integration. I had to go for my own package, because said python package was incompatible with my inverter, as it was using a different api.

Long story short: I think @pergolafabio is right and @Timme-72 is using a different kind of inverter with a different kind of api. Thus this package will not be compatible.
That also explains why the other integration is working and this one isn't :-)

**Comment by Timme-72** [comment]
Hey,
 sorry for the delay.
I have this WEB ![Unbenannt](https://github.com/scheidtdav/homeassistant-kostal-piko/assets/155076395/31d52db8-87c2-4597-a537-13e0325c3721)of my KOSTAL PIKO 5.5

**Comment by Timme-72** [comment]
Ok I will stay on rcasula ;-)

Thanks

**Comment by scheidtdav** [comment]
Alright, thanks for clarifying!
I'll make sure to update the README.
