### ISSUE TITLE
Kostal Piko 6.0 BA / how to change polling interval?

### ISSUE THREAD

**Issue by myraumhafen** [scheidtdav/homeassistant-kostal-piko#13]
Hello, 
many thanks for this integration. I'm new with Home Assistant (previously used FHEM) and I'm currently testing whether all my smart home components work with HA.
I have a Kostal Piko 6.0 BA with firmware 02.22. The integration seems to be working so far. 
But maybe a beginner question, how can I change the polling interval?
Thanks, Michael

**Comment by scheidtdav** [comment]
Hey,

welcome to Home Assistant! I have quite a similar journey behind me and did ask myself the exact same question when I was new to Home Assistant.

The polling interval is usually set per integration in Home Assistant. In the case of this integration, its 15 seconds (cp. [here](https://github.com/scheidtdav/homeassistant-kostal-piko/blob/6dbc141f9503c383a2c0959547384a0af4e279b5/custom_components/kostal_piko/__init__.py#L63)).
Because this is a custom integration (e.g. via HACS), you are technically able to change it by editing the file in your local Home Assistant instance. An update to the integration would however overwrite this.
I don't recommend going any lower than 15 seconds though, since from my testing the inverters really don't like that and will start to silently reject requests. That ultimately leads to the sensor switching its state to "unavailable".

I have seen people using time-based automation to update a sensor with an arbitrary interval, but I have no experience regarding that.


Hope that helps!

**Comment by myraumhafen** [comment]
Thank you for the feedback. That helps me. 15 seconds is more than enough. I thought the interval was set to 300 seconds since I only saw 5 minute intervals in the graphs. Then I have to take a closer look at it again to see whether the resolution in the diagrams can be further refined.

**Comment by scheidtdav** [comment]
You're welcome!
Totally possible that you only find 5 minute intervals, because the state doesn't change. Highly unlikely for e.g. the solar production though. If you happen to find any issues, feel free to come back here.
Happy to reopen this in that case.

Cheers
