### ISSUE TITLE
Cannot Install Due to Missing Version in Manifest

### ISSUE THREAD

**Issue by FrankUlbrich** [scheidtdav/homeassistant-kostal-piko#4]
Hi,
I would like to encourage you to work an your project.
On my side I am trying to get a 2013 Kostal Piko 7 FW<5 working
with homeassistant, but I still did not manage it.
Greetings
Frank

**Comment by scheidtdav** [comment]
Hi Frank,

thabks for your encouragement! I did commit a pull request to the main HomeAssistant repo. Unfortunately it is still open and not yet part of the core components, so I am thinking about extending and publishing it through HACS. Any help regarding that is welcome!

Regarding your Piko 7: Does it rely on the DXS api for the website? If so, it should be possible to use it with this component. Is there something specific you are struggling with?


Cheers

David

**Comment by dinomyte76** [comment]
Hi David,
i'd attach myself to this issue if you don't mind.

Unfortunately I'm struggling to get your integration to work. It seems that it won't be loaded:

`2023-05-13 00:20:52.406 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration kostal_piko which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-05-13 00:20:52.406 ERROR (SyncWorker_0) [homeassistant.loader] The custom integration 'kostal_piko' does not have a version key in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details
2023-05-13 00:20:55.214 ERROR (MainThread) [homeassistant.components.hassio.handler] /store return code 500
2023-05-13 00:20:55.220 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /store -
`
Any idea what this could be? I've downloaded your integration by adding your github (https://github.com/scheidtdav/homeassistant-kostal-piko) as Custom Repository in HACS and hitting the "Download" Button. When reloading HA, i get the above message in the log.

Thanks a lot in advance! 

Greets Dino

**Comment by dinomyte76** [comment]
I tried some further things, e. g. i added a version tag in manifest.json. After that the integration was successfully loaded, but when adding the necessary parts in configuration.yaml, the log told me that this is not supported by this integration.
@scheidtdav I assume this is because the last version is supposed to be integrated as official integration and therefore should be administrated through the integration frontend?

However, it tried als your prototype version from here: https://github.com/scheidtdav/homeassistant-kostal-piko/issues/2#issuecomment-955671133
But also this i coulödn't get to work :-( the log printed something like "timeout to the kostal ip XYZ", although when fetching the dxsEntries as http request directly from the brwoser works fine for me...

I guess i need to wait until the release of your official integration...

**Comment by scheidtdav** [comment]
Hey @dinomyte76 and @FrankUlbrich,

I had some time to have a look at this repo. I realized it wasn't up to date with what I had passed to the Home Assistant core repository. I have updated it since and also tested everything locally in a development environment. So far, it seems to work fine on my side and I'd be interested in your findings.

Check out [the latest release](https://github.com/scheidtdav/homeassistant-kostal-piko/releases/tag/2023.05.1) to get it started.
Easiest installation is via HACS as a custom integration.

@dinomyte76 Regarding configuration through the UI, you are right. The latest version does not require any configuration through a yaml file or anything.


Cheers
